"""为ppx_storage_var表建立唯一约束字段

Revision ID: 802ec4ff5306
Revises: a69c80be508b
Create Date: 2025-02-11 15:03:04.314219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802ec4ff5306'
down_revision = 'a69c80be508b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ppx_storage_var_key', table_name='ppx_storage_var')
    op.create_index(op.f('ix_ppx_storage_var_key'), 'ppx_storage_var', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ppx_storage_var_key'), table_name='ppx_storage_var')
    op.create_index('ix_ppx_storage_var_key', 'ppx_storage_var', ['key'], unique=False)
    # ### end Alembic commands ###
