"""新增ppx_storage_var表

Revision ID: a69c80be508b
Revises: 96ee93975f8a
Create Date: 2023-04-12 20:41:54.090548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69c80be508b'
down_revision = '96ee93975f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppx_storage_var',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('val', sa.String(), server_default='', nullable=False),
    sa.Column('remark', sa.String(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppx_storage_var_key'), 'ppx_storage_var', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ppx_storage_var_key'), table_name='ppx_storage_var')
    op.drop_table('ppx_storage_var')
    # ### end Alembic commands ###
